version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
networks:
  backend:
